; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:bluepill_f103c8]
upload_flags = 
    -c set CPUTAPID 0x0
    -c reset_config none

platform = ststm32
board = bluepill_f103c8
framework = arduino

; 指定烧录工具为 ST-Link
upload_protocol = stlink

; 串口监视器设置（针对你的 CH340）
monitor_speed = 115200

; 库依赖
lib_deps = 
	adafruit/Adafruit PN532 @ ^1.3.4
	adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/DHT sensor library @ ^1.4.6
    Wire